### ISSUE TITLE
☄️ EPIC: Valkyrize Hyku

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/hykuup_knapsack#35]
# Summary
Valkyrize Hyku

base epic off of Hyku/hyrax-5-upgrade:
- branch: i35-valkyrize-hyku

## Prerequisite
- [x] #65 

# Tasks
Quick notes from planning meeting with Rob on 12/15. These tasks are NOT to be worked on until #65 is complete

### Divide and Conquer where it makes sense. Tasks to valkyrize Hyku include...
- [x] #80
- [x] #79
  - [x] ref GBH for example
  - [x] Set up valkyrie config to use freya adapter (see gbh version for template)
- [x] #81
- [x] #85
  - [x] #87
  - [x] #88
  - [x] #89
  - [x] #90
  - [x] #91
  - [x] #92
  - [ ] #100
    - [ ] When clicking edit on a GenericWork, it should redirect you to GenericWorkResource. 
    - [ ] Clicking save on GenericWorkResource should go to the GenercWorkResource controller #create
    - [ ] ref [GBH](https://github.com/WGBH-MLA/ams/blob/develop/config/routes.rb#L3-L5)
- [x] #82
- [x] #94
- [x] #83
- [ ] #110
- [ ] Add Hyrax::Works::ValkyrieMigration module to the resource models (to fix polymorphic issue)
- [ ] correct generator. form should inherit from hyrax::resourceform
- [ ] Add Hyku::WorksControllerBehavior to the controllers
- [ ] add self.show_presenter = Hyku::WorkShowPresenter to works_controller_behavior.rb
- [ ] HykuIndexing needs to be updated for ruby3+
- [ ] AdminSets needs work
- [ ] Update seed file to support valkyrie? 
- [ ] #107
- [ ] double_combo + main. Get specs passing
- [x] #111

### Reconnect as a team before proceeding
- [x] test that creating new resource based works is functioning from the rails console and in the UI
- [ ] find all references left to AF models and change them to use Valkyrie versions (this may be just adding 'Resource' to the class call or it may be using the query_service or persisters)
- [ ] - See what’s broken and needs to be fixed
- [ ] #109
- [x] - Add routes redirects to prevent hitting the AF show or edit pages
  - [x] When clicking edit on a GenericWork, it should redirect you to GenericWorkResource. 
- [ ] - Write instructions for how to make a resource version for your existing models
- [ ] - **Note**: The Thing that’s missing is making file sets work for valkyrie. How to migrate them from fedora to Postgres?
- [x] - Rob will make a list of how to valkyrie the application for us to work on while he works on the file set portion. 
- [ ] - Port reprocessor to either Hyrax or Hyku
- [ ] document how to valkyrize the app

## MISC
- [x] solr core doesn't delete when tenant gets deleted
- [ ] https://github.com/scientist-softserv/iiif_print/issues/312
- [ ] #86 
- [x] https://github.com/scientist-softserv/hykuup_knapsack/issues/34
- [x] https://github.com/scientist-softserv/hykuup_knapsack/issues/93
- [ ] #101
- [ ] Consider changes to roles_service (Collection vs PcdmCollection & AdminSet vs AdministrativeSet)
- [ ] hyku/works_controller_behavior theming failures in method inject_show_theme_views
- [x] can't delete a tenant in proprieter page (confirmation messages says deleted but it still exists)
- [ ] collection banners do not work (`No such file or directory @ rb_sysopen - /uploads/09e34f56-19d6-4916-9a5f-e7afe17ed212/hyrax/uploaded_file/file/2/banner2.jpeg`)

# Notes

Updated list of TODOs per 1/25/24: 
Task review [spreadsheet](https://docs.google.com/spreadsheets/d/1R8KIR4YPh58MBfNaVIkkpZ62cVCNJ9wXtsCMt4irGd0/edit#gid=0)

### Bulkrax
- https://github.com/scientist-softserv/hykuup_knapsack/issues/128
- https://github.com/scientist-softserv/hykuup_knapsack/issues/124
- https://github.com/scientist-softserv/hykuup_knapsack/issues/120
- https://github.com/scientist-softserv/hykuup_knapsack/issues/136

### IIIF Print
- https://github.com/scientist-softserv/iiif_print/issues/312
- https://github.com/scientist-softserv/iiif_print/issues/325

### Hyrax
- https://github.com/scientist-softserv/hykuup_knapsack/issues/34
- https://github.com/scientist-softserv/hykuup_knapsack/issues/127

### HYKU
-  https://github.com/scientist-softserv/hykuup_knapsack/issues/35
- https://github.com/scientist-softserv/hykuup_knapsack/issues/129
- https://github.com/scientist-softserv/hykuup_knapsack/issues/132
- https://github.com/scientist-softserv/hykuup_knapsack/issues/109
- https://github.com/scientist-softserv/hykuup_knapsack/issues/126
- https://github.com/scientist-softserv/hykuup_knapsack/issues/131
- https://github.com/scientist-softserv/hykuup_knapsack/issues/94
- https://github.com/scientist-softserv/hykuup_knapsack/issues/123
- https://github.com/scientist-softserv/hykuup_knapsack/issues/122
- https://github.com/scientist-softserv/hykuup_knapsack/issues/121
- https://github.com/scientist-softserv/hykuup_knapsack/issues/120
- https://github.com/scientist-softserv/hykuup_knapsack/issues/119
- https://github.com/scientist-softserv/hykuup_knapsack/issues/118
- https://github.com/scientist-softserv/hykuup_knapsack/issues/117
- https://github.com/scientist-softserv/hykuup_knapsack/issues/116
- https://github.com/scientist-softserv/hykuup_knapsack/issues/115
- https://github.com/scientist-softserv/hykuup_knapsack/issues/130

**Comment by ShanaLMoore** [comment]
TODO per standup: set up 30 min call with Rob, collaborate an outline of what needs to happen. reference GBH.

**Comment by ShanaLMoore** [comment]
Valkrize Hyku Meeting notes: https://docs.google.com/document/d/1WCB-5qIDCGhMQSuAzM70MDIuP4EQJhtnvgZt2x8MS4o/edit

**Comment by ShanaLMoore** [comment]
deployed to https://hyku-staging.notch8.cloud/

**Comment by ShanaLMoore** [comment]
Remaining work: https://docs.google.com/spreadsheets/d/1R8KIR4YPh58MBfNaVIkkpZ62cVCNJ9wXtsCMt4irGd0/edit#gid=0

**Comment by ShanaLMoore** [comment]
Hyku has been valyrized and released with v6.0.0rc3. Bulkrax released valkyrie support with v8.0.0
